# Generated by Django 4.1.9 on 2023-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servies_icon', models.CharField(max_length=50)),
                ('servies_title', models.CharField(max_length=50)),
                ('servies_des', models.TextField()),
            ],
        ),
    ]
