# Generated by Django 4.1.7 on 2023-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servies',
            name='servies_icon',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='project/'),
        ),
    ]
