# Generated by Django 4.1.9 on 2023-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servies', '0002_alter_servies_servies_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servies',
            name='servies_git_url',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
