# Generated by Django 5.0 on 2024-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servies", "0003_servies_servies_git_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContectUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_mobile", models.CharField(max_length=15)),
                ("user_email", models.EmailField(max_length=70, unique=True)),
                ("user_message", models.CharField(max_length=200)),
            ],
        ),
    ]
